# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_pandas": "01_klass.ipynb",
         "avled_tverrvar": "03_sporre.ipynb",
         "freq": "04_proc.ipynb"}

modules = ["klass.py",
           "sporre.py",
           "proc.py"]

doc_url = "https://statisticsnorway.github.io/ssb_fellesfunksjoner_360//ssb_fellesfunksjoner_360/"

git_url = "https://github.com/statisticsnorway/ssb_fellesfunksjoner_360/"

def custom_doc_links(name): return None
