# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_pandas": "00_klass.ipynb"}

modules = ["klass.py"]

doc_url = "https://statisticsnorway.github.io/ssb_fellesfunksjoner_360//ssb_fellesfunksjoner_360/ssb_fellesfunksjoner_360/"

git_url = "https://github.statisticsnorway.com/ssb_fellesfunksjoner_360/tree/Prod/"

def custom_doc_links(name): return None
