# AUTOGENERATED! DO NOT EDIT! File to edit: 00_klass.ipynb (unless otherwise specified).

__all__ = ['get_pandas']

# Cell
# Med "export"-kommentaren over så blir koden med i både modulen som eksporteres og dokumentasjonen.
def get_pandas(URL, level):
    import requests, json, pandas as pd
    r = requests.get(URL)
    r = r.content.decode('utf8').replace("'", '"')
    r = json.loads(r)
    r = pd.json_normalize(r[level])
    return r

# Cell
